# Generated by Django 4.2.17 on 2025-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('derivered', 'Derivered'), ('cancelled', 'Canselled')], default='pending', max_length=50),
        ),
    ]
