# Generated by Django 4.2.17 on 2025-06-03 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text="Phone number must be entered in the format: '+99123654'. Up to 20 digits.", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99123654'. Up to 20 digits.", regex='^\\+?1?\\d{9,20}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
